name: Backend CI/CD

on:
  push:
    paths:
      - 'Task2/apz-pzpi-21-1-boichenko-matvii-task2/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd Task2/apz-pzpi-21-1-boichenko-matvii-task2
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd Task2/apz-pzpi-21-1-boichenko-matvii-task2
          # Add your test command here
          pytest

      - name: Build Docker image
        run: |
          cd Task2/apz-pzpi-21-1-boichenko-matvii-task2
          docker build -t ${{ secrets.CONTAINER_REGISTRY }}.azurecr.io/fastapi-backend:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.CONTAINER_REGISTRY }}.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin
          docker push ${{ secrets.CONTAINER_REGISTRY }}.azurecr.io/fastapi-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        run: |
          az webapp config container set --name ${{ secrets.WEB_APP_BACKEND }} --resource-group ${{ secrets.RESOURCE_GROUP }} --docker-custom-image-name ${{ secrets.CONTAINER_REGISTRY }}.azurecr.io/fastapi-backend:latest --docker-registry-server-url https://{{ secrets.CONTAINER_REGISTRY }}.azurecr.io --docker-registry-server-user ${{ secrets.ACR_USERNAME }} --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
