name: Delete Azure Resources

on:
  workflow_dispatch:

jobs:
  delete-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Azure Resources
        run: |
          az group delete --name ${{ secrets.RESOURCE_GROUP }} --yes --no-wait
